/*
  # Insert sample products into products_enriched table

  1. Sample Data
    - Insert 3 sample products with complete attributes
    - All products have stock > 0 and proper pricing
    - Images and URLs are valid examples
  
  2. Data Structure
    - Uses all available columns from products_enriched schema
    - Includes enriched attributes (colors, materials, styles)
    - SEO and Google Shopping attributes populated
*/

INSERT INTO products_enriched (
    handle,
    title,
    description,
    category,
    subcategory,
    type,
    color,
    material,
    fabric,
    style,
    dimensions,
    room,
    price,
    stock_qty,
    stock_quantity,
    image_url,
    product_url,
    tags,
    seo_title,
    seo_description,
    ad_headline,
    ad_description,
    google_product_category,
    gtin,
    brand,
    confidence_score,
    enriched_at,
    enrichment_source
) VALUES
    (
        'canape-moderne-beige',
        'Canapé Moderne 3 Places - Beige',
        'Canapé confortable en tissu beige avec structure en bois massif. Design contemporain parfait pour salon moderne.',
        'Canapé',
        'Canapé 3 places',
        'Mobilier',
        'Beige, Naturel',
        'Bois massif, Tissu',
        'Tissu texturé',
        'Moderne, Contemporain',
        '200x90x85cm',
        'Salon',
        899.99,
        15,
        15,
        'https://images.pexels.com/photos/1350789/pexels-photo-1350789.jpeg?auto=compress&cs=tinysrgb&w=400&h=400&fit=crop',
        'https://exemple.com/canape-moderne-beige',
        ARRAY['moderne', 'salon', 'confort', '3-places', 'beige'],
        'Canapé Moderne Beige 3 Places - Confort Premium',
        'Découvrez notre canapé moderne 3 places en tissu beige. Design contemporain et confort optimal pour votre salon.',
        'Canapé Moderne Premium',
        'Tissu beige premium, structure bois massif, design contemporain élégant.',
        'Furniture > Living Room Furniture > Sofas',
        '3701234567890',
        'Decora Home',
        92,
        now(),
        'manual'
    ),
    (
        'table-ronde-chene',
        'Table Ronde en Chêne Ø120cm',
        'Table à manger ronde en chêne massif avec finition naturelle. Pieds tournés traditionnels.',
        'Table',
        'Table à manger',
        'Mobilier',
        'Chêne naturel, Bois clair',
        'Chêne massif',
        '',
        'Classique, Traditionnel',
        'Ø120x75cm',
        'Salle à manger',
        649.99,
        8,
        8,
        'https://images.pexels.com/photos/1571460/pexels-photo-1571460.jpeg?auto=compress&cs=tinysrgb&w=400&h=400&fit=crop',
        'https://exemple.com/table-ronde-chene',
        ARRAY['chêne', 'ronde', 'traditionnel', 'salle-a-manger'],
        'Table Ronde Chêne Massif Ø120cm - Artisanat Français',
        'Table à manger ronde en chêne massif français. Finition naturelle, pieds tournés. Parfaite pour 6 personnes.',
        'Table Chêne Artisanal',
        'Chêne massif français, finition naturelle, pieds tournés traditionnels.',
        'Furniture > Tables > Dining Tables',
        '3701234567891',
        'Decora Home',
        88,
        now(),
        'manual'
    ),
    (
        'fauteuil-scandinave-gris',
        'Fauteuil Scandinave - Gris Clair',
        'Fauteuil au design scandinave en tissu gris clair avec pieds en bois naturel. Confort optimal et style nordique.',
        'Fauteuil',
        'Fauteuil salon',
        'Mobilier',
        'Gris clair, Bois naturel',
        'Bois naturel, Tissu',
        'Tissu chenille',
        'Scandinave, Nordique',
        '75x80x85cm',
        'Salon',
        299.99,
        12,
        12,
        'https://images.pexels.com/photos/586763/pexels-photo-586763.jpeg?auto=compress&cs=tinysrgb&w=400&h=400&fit=crop',
        'https://exemple.com/fauteuil-scandinave-gris',
        ARRAY['scandinave', 'gris', 'confort', 'salon', 'nordique'],
        'Fauteuil Scandinave Gris - Design Nordique Authentique',
        'Fauteuil scandinave en tissu gris clair avec pieds bois naturel. Style nordique authentique et confort optimal.',
        'Fauteuil Scandinave',
        'Design nordique, tissu gris premium, pieds bois naturel.',
        'Furniture > Chairs > Accent Chairs',
        '3701234567892',
        'Decora Home',
        90,
        now(),
        'manual'
    );